// src/CHIPProjectAppConfig.h
#pragma once
// #include <platform/Linux/CHIPLinuxProjectConfig.h>

// --- Force BLE off (don’t include any BlueZ/GIO bits) ---
#ifdef CHIP_DEVICE_CONFIG_ENABLE_CHIPOBLE
#undef CHIP_DEVICE_CONFIG_ENABLE_CHIPOBLE
#endif
#define CHIP_DEVICE_CONFIG_ENABLE_CHIPOBLE 0

// (rest stays the same)
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME "Dtack"
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID 0xFFF1
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME "Dt Counter"
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID 0x8000
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 20202021
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR 3840
