name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/david-erb/docker30-linux1:latest
    strategy:
      matrix:
        app: [test_all]
    steps:
      - uses: actions/checkout@v5
      - name: Run
        run: bash scripts/ci_linux.sh ${{ matrix.app }}
      - name: Upload coverage
        if: matrix.app == 'test_all'
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
